### ISSUE TITLE
Dice Tray does not install via FVTT 12 built-in installer

### ISSUE THREAD

**Issue by slottwo** [mclemente-organization/fvtt-dice-tray#17]
Foundry Version 12 Stable - Build 324
Dice Tray (on Foundry "Shop") Version 1.5.3

When trying to install the module through the app in the catalog, the error below appears and the add-on is not installed:

```
Uncaught (in promise) Error: An unexpected error occurred when downloading file https://gitlab.com/asacolips-projects/foundry-mods/foundry-vtt-dice-calculator/-/archive/1.5.3/foundry-vtt-dice-calculator-master.zip: Not Acceptable
    at fetchWithTimeout (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/http.mjs:48:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/files/downloader.mjs:1:631
```

But the manual way still works. (via the manifest link on [README.md](https://github.com/mclemente/fvtt-dice-tray/blob/master/README.md))

**Comment by mclemente** [comment]
This issue has been fixed now. Thank you for reporting it.
